services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_iam_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      - postgres
      - mongo
    command: ["pnpm", "start:dev"]
